name: S3 Data Ingestion
on:
  workflow_dispatch:
  push:
    branches: [ main ]  
jobs:
  ingest_data:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1
    - name: Terraform Init
      run: |
        shell: bash 
        cd Lambda/
        shell: bash 
        terraform init
    - name: Terraform Apply
      run: terraform apply -auto-approve
